/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LearnroutImport } from './routes/learn_rout'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LearnroutRoute = LearnroutImport.update({
  id: '/learn_rout',
  path: '/learn_rout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/learn_rout': {
      id: '/learn_rout'
      path: '/learn_rout'
      fullPath: '/learn_rout'
      preLoaderRoute: typeof LearnroutImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn_rout': typeof LearnroutRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn_rout': typeof LearnroutRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/learn_rout': typeof LearnroutRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learn_rout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn_rout'
  id: '__root__' | '/' | '/learn_rout'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnroutRoute: typeof LearnroutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnroutRoute: LearnroutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/learn_rout"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/learn_rout": {
      "filePath": "learn_rout.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
